#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
#  build-menubar-app.sh  —  Bundle the menubar app as Ludos Sync.app
#
#  Usage:
#    ./build-menubar-app.sh                    Build with ad-hoc signing
#    ./build-menubar-app.sh --sign <CERT_ID>   Build with Developer ID signing
#    ./build-menubar-app.sh --clean            Move all build artifacts to to_delete/
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MENUBAR_DIR="$SCRIPT_DIR/packages/ludos-sync-menubar"
BUILDS_DIR="$SCRIPT_DIR/builds"
TRASH_DIR="$MENUBAR_DIR/to_delete"
LOGO_SRC="$SCRIPT_DIR/imgs/logo.png"

SIGN_ID=""
CLEAN=false

# Helper: move items to to_delete/ instead of rm -rf
trash() {
  mkdir -p "$TRASH_DIR"
  for item in "$@"; do
    if [ -e "$item" ]; then
      dest="$TRASH_DIR/$(basename "$item")"
      # If destination already exists, add a timestamp suffix
      if [ -e "$dest" ]; then
        dest="${dest}_$(date +%s)"
      fi
      mv "$item" "$dest"
    fi
  done
}

# ── Parse flags ──────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --clean)  CLEAN=true; shift ;;
    --sign)   SIGN_ID="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,8p' "$0" | sed 's/^#  //'
      exit 0 ;;
    *)
      echo "Unknown option: $1"; exit 1 ;;
  esac
done

cd "$MENUBAR_DIR"

# ── Clean mode ───────────────────────────────────────────────────
if $CLEAN; then
  echo "Moving build artifacts to to_delete/…"
  trash dist build venv logo.icns logo.iconset logo.png _buildconfig.py
  trash "$BUILDS_DIR/Ludos Sync.app"
  echo "Done. You can delete $TRASH_DIR when ready."
  exit 0
fi

# ── 0. Clear previous intermediate artifacts ─────────────────────
trash dist build logo.iconset logo.icns _buildconfig.py

# ── 1. Create venv & install deps ───────────────────────────────
if [ ! -d venv ]; then
  echo "Creating venv…"
  python3 -m venv venv
fi
source venv/bin/activate
pip install --quiet rumps py2app

# ── 2. Convert logo.png → logo.icns ─────────────────────────────
echo "Generating app icon…"
mkdir logo.iconset
for size in 16 32 64 128 256 512; do
  sips -z $size $size "$LOGO_SRC" --out "logo.iconset/icon_${size}x${size}.png" >/dev/null 2>&1
  double=$((size * 2))
  sips -z $double $double "$LOGO_SRC" --out "logo.iconset/icon_${size}x${size}@2x.png" >/dev/null 2>&1
done
iconutil -c icns logo.iconset -o logo.icns

# ── 3. Copy logo.png for bundling as resource ───────────────────
cp "$LOGO_SRC" logo.png

# ── 4. Generate _buildconfig.py ──────────────────────────────────
cat > _buildconfig.py <<PYEOF
# Auto-generated by build-menubar-app.sh — do not edit
PROJECT_ROOT = "$SCRIPT_DIR"
PYEOF
echo "Generated _buildconfig.py (PROJECT_ROOT=$SCRIPT_DIR)"

# ── 5. Build the .app ───────────────────────────────────────────
echo "Building Ludos Sync.app…"
python setup.py py2app

# ── 6. Code-sign ────────────────────────────────────────────────
APP_PATH="dist/Ludos Sync.app"

if [ -n "$SIGN_ID" ]; then
  echo "Signing with Developer ID: $SIGN_ID"
  codesign -s "$SIGN_ID" \
    --force --deep \
    --options runtime \
    --entitlements entitlements.plist \
    "$APP_PATH"
  echo ""
  echo "Signed. To distribute, notarize with:"
  echo "  xcrun notarytool submit \"$BUILDS_DIR/Ludos Sync.app\" --apple-id YOU@EMAIL --team-id TEAMID --wait"
  echo "  xcrun stapler staple \"$BUILDS_DIR/Ludos Sync.app\""
else
  echo "Ad-hoc signing…"
  codesign -s - --force --deep "$APP_PATH"
fi

# ── 7. Move .app to builds/ ──────────────────────────────────────
mkdir -p "$BUILDS_DIR"
trash "$BUILDS_DIR/Ludos Sync.app"
mv "$APP_PATH" "$BUILDS_DIR/"

# ── 8. Cleanup generated/intermediate files ──────────────────────
trash logo.iconset logo.icns logo.png _buildconfig.py dist build

FINAL_APP="$BUILDS_DIR/Ludos Sync.app"
echo ""
echo "Build complete: $FINAL_APP"
codesign -v "$FINAL_APP" && echo "Signature valid." || echo "Warning: signature verification failed."
