#!/usr/bin/env bash
# Build the Ludos Sync menubar app (.app bundle) and install it.
#
# Steps:
#   1. Build the ludos-sync server (TypeScript → dist/)
#   2. Generate _buildconfig.py with PROJECT_ROOT
#   3. Generate logo.icns from logo.png
#   4. Run py2app to create the .app bundle
#   5. Ad-hoc code sign with entitlements
#   6. Stop running instance, install to builds/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
MENUBAR_DIR="$SCRIPT_DIR"
SYNC_DIR="$PROJECT_ROOT/packages/ludos-sync"
BUILDS_DIR="$PROJECT_ROOT/builds"
APP_NAME="Ludos Sync"
VENV_DIR="$MENUBAR_DIR/venv"

echo "==> Building $APP_NAME"
echo "    Project root: $PROJECT_ROOT"
echo ""

# ── 1. Build ludos-sync server ────────────────────────────────
echo "==> Building ludos-sync server (TypeScript)…"
(cd "$SYNC_DIR" && npm run build)
echo ""

# ── 2. Generate _buildconfig.py ───────────────────────────────
echo "==> Generating _buildconfig.py…"
cat > "$MENUBAR_DIR/_buildconfig.py" <<PYEOF
# Auto-generated by build-menubar-app.sh — do not edit
PROJECT_ROOT = "$PROJECT_ROOT"
PYEOF
echo ""

# ── 3. Generate logo.icns ─────────────────────────────────────
LOGO_SRC="$PROJECT_ROOT/imgs/logo.png"
ICONSET_DIR="$MENUBAR_DIR/logo.iconset"

if [[ ! -f "$MENUBAR_DIR/logo.icns" ]] || [[ "$LOGO_SRC" -nt "$MENUBAR_DIR/logo.icns" ]]; then
    echo "==> Generating logo.icns…"
    rm -rf "$ICONSET_DIR"
    mkdir -p "$ICONSET_DIR"

    for size in 16 32 64 128 256 512; do
        sips -z "$size" "$size" "$LOGO_SRC" --out "$ICONSET_DIR/icon_${size}x${size}.png" >/dev/null 2>&1
        double=$((size * 2))
        sips -z "$double" "$double" "$LOGO_SRC" --out "$ICONSET_DIR/icon_${size}x${size}@2x.png" >/dev/null 2>&1
    done

    iconutil -c icns "$ICONSET_DIR" -o "$MENUBAR_DIR/logo.icns"
    rm -rf "$ICONSET_DIR"
else
    echo "==> logo.icns is up to date"
fi

# Ensure logo.png is in menubar dir for py2app resources
cp -f "$LOGO_SRC" "$MENUBAR_DIR/logo.png"
echo ""

# ── 4. Set up venv and run py2app ─────────────────────────────
echo "==> Building .app bundle with py2app…"

if [[ ! -d "$VENV_DIR" ]]; then
    echo "    Creating virtual environment…"
    python3 -m venv "$VENV_DIR"
fi

source "$VENV_DIR/bin/activate"
pip install -q rumps py2app

# Always clean before build so py2app produces a fresh bundle
rm -rf "$MENUBAR_DIR/build" "$MENUBAR_DIR/dist"

(cd "$MENUBAR_DIR" && python setup.py py2app 2>&1 | tail -5)
echo ""

# ── 5. Ad-hoc code sign ───────────────────────────────────────
APP_BUNDLE="$MENUBAR_DIR/dist/$APP_NAME.app"
if [[ ! -d "$APP_BUNDLE" ]]; then
    echo "ERROR: py2app did not produce $APP_BUNDLE"
    exit 1
fi

echo "==> Code signing (ad-hoc)…"
codesign --force --deep --sign - \
    --entitlements "$MENUBAR_DIR/entitlements.plist" \
    "$APP_BUNDLE"
echo ""

# ── 6. Install to builds/ ─────────────────────────────────────
echo "==> Installing to $BUILDS_DIR/"
mkdir -p "$BUILDS_DIR"

# Stop running instance
if pgrep -f "$APP_NAME.app/Contents/MacOS" >/dev/null 2>&1; then
    echo "    Stopping running instance…"
    pkill -f "$APP_NAME.app/Contents/MacOS" || true
    sleep 1
fi

rm -rf "$BUILDS_DIR/$APP_NAME.app"
cp -R "$APP_BUNDLE" "$BUILDS_DIR/$APP_NAME.app"

# Clean up build intermediates
rm -rf "$MENUBAR_DIR/build" "$MENUBAR_DIR/dist" "$MENUBAR_DIR/_buildconfig.py"

echo ""
echo "==> Done! Launch with:"
echo "    open \"$BUILDS_DIR/$APP_NAME.app\""
